version: "3"
services:
  localstack:
    image: localstack/localstack:1.3
    networks:
      - hmpps
    container_name: localstack-oe
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - SERVICES=sns,sqs
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - $PWD/src/test/resources/localstack:/docker-entrypoint-initaws.d

networks:
  hmpps:
