apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-queue-housekeeping-cronjob
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  # At every 10th minute from 1 through 59 past every hour from 7 through 20 UTC on every day-of-week from Monday through Friday.
  schedule: "1-59/10 07-20 * * 1-5"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: retryalldlqs
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://prison-offender-events/queue-admin/retry-all-dlqs
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
