apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.secrets.APPINSIGHTS_INSTRUMENTATIONKEY | b64enc | quote }}
  OFFENDER_EVENTS_CLIENT_SECRET: {{ .Values.secrets.OFFENDER_EVENTS_CLIENT_SECRET | b64enc | quote }}
  OFFENDER_EVENTS_CLIENT_ID: {{ .Values.secrets.OFFENDER_EVENTS_CLIENT_ID | b64enc | quote }}
