
oauth:
  api.base.url: ${OAUTH_API_BASE_URL:http://localhost:9090/auth}
custody:
  api.base.url: ${CUSTODY_API_BASE_URL:http://localhost:8081}

custodyapi:
  client:
    clientId: ${OFFENDER_EVENTS_CLIENT_ID:offender-events-client}
    clientSecret: ${OFFENDER_EVENTS_CLIENT_SECRET:clientsecret}