spring:
  profiles:
    group:
      test:
        - "stdout"
  application:
    name: hmpps-prison-offender-events

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${api.base.url.hmpps-auth}/.well-known/jwks.json

      client:
        registration:
          prison-api:
            provider: hmpps-auth
            client-id: ${offender.events.client.id}
            client-secret: ${offender.events.client.secret}
            authorization-grant-type: client_credentials
            scope: read
        provider:
          hmpps-auth:
            token-uri: ${api.base.url.hmpps-auth}/oauth/token

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol_header: x-forwarded-proto

  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
aws:
  provider: aws
  region: eu-west-2

application:
  listener:
    totalDelayDuration: PT10M
    delayDuration: PT2M
