
api.base.url:
  hmpps-auth: ${API_BASE_URL_HMPPS_AUTH:http://localhost:9090/auth}
  prison: ${API_BASE_URL_PRISON:http://localhost:8081}
  casenotes: ${API_BASE_URL_CASENOTES:http://localhost:8083}

offender.events:
  client:
    id: ${OFFENDER_EVENTS_CLIENT_ID:offender-events-client}
    secret: ${OFFENDER_EVENTS_CLIENT_SECRET:clientsecret}
