hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4566
  queues:
    prisonEventQueue:
      topicArn: arn:aws:sns:eu-west-2:000000000000:dps-topic
      queueName: dps-queue
      dlqName: dps-dlq
    hmppsDomainEventQueue:
      topicArn: arn:aws:sns:eu-west-2:000000000000:hmpps-topic
      queueName: hmpps-queue
      dlqName: hmpps-dlq

aws:
  provider: localstack
