
oauth:
  api.base.url: ${OAUTH_API_BASE_URL:http://localhost:9090/auth}
prison:
  api.base.url: ${PRISON_API_BASE_URL:http://localhost:8081}

offender.events:
  client:
    id: ${OFFENDER_EVENTS_CLIENT_ID:offender-events-client}
    secret: ${OFFENDER_EVENTS_CLIENT_SECRET:clientsecret}
