spring:
  profiles:
    group:
      test:
        - "stdout"
  application:
    name: prison-offender-events

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: OFFENDER_EVENTS
    locations: classpath:/db/migration/h2,classpath:/db/migration/common
    url: 'jdbc:h2:mem:prison-offender-events-db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1'
    user: sa
    password: ''
    placeholders:
      database_password: dummy

  datasource:
    # This reopens the H2 database prepared by flyway with default schema and user OFFENDER_EVENTS
    url: 'jdbc:h2:mem:prison-offender-events-db;MODE=PostgreSQL;SCHEMA=OFFENDER_EVENTS;IFEXISTS=TRUE'
    username: offender_events
    password: dummy

    hikari:
      pool-name: OffenderEvents-CP
      connectionTimeout: 1000
      validationTimeout:  500

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.api.base.url}/.well-known/jwks.json

      client:
        registration:
          prison-api:
            provider: hmpps-auth
            client-id: ${offender.events.client.id}
            client-secret: ${offender.events.client.secret}
            authorization-grant-type: client_credentials
            scope: read
          community-api:
            provider: hmpps-auth
            client-id: ${offender.events.client.id}
            client-secret: ${offender.events.client.secret}
            authorization-grant-type: client_credentials
        provider:
          hmpps-auth:
            token-uri: ${oauth.api.base.url}/oauth/token
  sql:
    init:
      continue-on-error: false

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol_header: x-forwarded-proto

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    uk.gov.justice.hmpps: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health, ping'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms

cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
aws:
  provider: aws
  region: eu-west-2
hmpps.sqs:
  provider: ${aws.provider}
  region: ${aws.region}
  queueAdminRole: ROLE_QUEUE_ADMIN
  queues:
    prisonEventQueue:
      queueName: ${sqs.queue.name}
      queueAccessKeyId: ${sqs.aws.access.key.id}
      queueSecretAccessKey: ${sqs.aws.secret.access.key}
      dlqName: ${sqs.dlq.name}
      dlqAccessKeyId: ${sqs.aws.dlq.access.key.id}
      dlqSecretAccessKey: ${sqs.aws.dlq.secret.access.key}
  topics:
    prisonEventTopic:
      topicAccessKeyId: ${sns.aws.access.key.id}
      topicSecretAccessKey: ${sns.aws.secret.access.key}
      topicArn: ${sns.topic.arn}
    hmppsEventTopic:
      topicAccessKeyId: ${hmpps.sns.aws.access.key.id}
      topicSecretAccessKey: ${hmpps.sns.aws.secret.access.key}
      topicArn: ${hmpps.sns.topic.arn}


application:
  listener:
    totalDelayDuration: PT10M
    delayDuration: PT2M

  events:
    max:
      range:
        minutes: 20
    poll:
      frequency: 60000
      initialDelay: 2000
      lockAtLeastFor: PT10S
