version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@8

jobs:
  validate:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "2.3"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - run:
          name: Wait for SQS and SNS to be ready
          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4566
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - helm_lint
            - build_docker
      - hmpps/smoke_test:
          context: hmpps-smoketest-common-vars
          name: smoke_test
          jdk_tag: "21.0"
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - prison-offender-events-preprod
          requires:
            - smoke_test
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          context:
            - hmpps-common-vars
            - prison-offender-events-prod
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "45 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          cache_key: "v2_0"
          jdk_tag: "21.0"
          slack_channel: syscon-alerts
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: syscon-alerts
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: syscon-alerts
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "30 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: syscon-alerts
          context:
            - veracode-credentials
            - hmpps-common-vars

