# Values here are the same across all environments
generic-service:
  nameOverride: prison-offender-events
  productId: DPS060

  image:
    repository: quay.io/hmpps/prison-offender-events
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    tlsSecretName: offender-events-cert

  serviceAccountName: prison-offender-events

  env:
    JAVA_OPTS: "-Xmx512m"
    AWS_REGION: "eu-west-2"
    SPRING_PROFILES_ACTIVE: "sns"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    HMPPS_SQS_USE_WEB_TOKEN: true

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    prison-offender-events:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OFFENDER_EVENTS_CLIENT_SECRET: "OFFENDER_EVENTS_CLIENT_SECRET"
      OFFENDER_EVENTS_CLIENT_ID: "OFFENDER_EVENTS_CLIENT_ID"
    offender-events-topic:
      HMPPS_SQS_TOPICS_PRISONEVENTTOPIC_ARN: "topic_arn"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    prisoner-offender-events-queue:
      HMPPS_SQS_QUEUES_PRISONEVENTQUEUE_QUEUE_NAME: "sqs_queue_name"
    prisoner-offender-events-dlq:
      HMPPS_SQS_QUEUES_PRISONEVENTQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: prison-offender-events
  sqsAlertsTotalMessagesThreshold: 1
