# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/prison-offender-events
  tag: latest
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: offender-events.prison.service.justice.gov.uk
      cert_secret: offender-events-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  PRISON_API_BASE_URL: "https://api.prison.service.justice.gov.uk"
  COMMUNITY_API_BASE_URL: "https://community-api.probation.service.justice.gov.uk"
  OAUTH_API_BASE_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  WIND_BACK_SECONDS: "400"
  APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# determine which slack channel alerts are sent to, via the correct Alert Manager receiver
generic-prometheus-alerts:
  alertSeverity: digital-prison-service

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
