---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: offender-events-dev.prison.service.justice.gov.uk

  allowlist: null

  env:
    PRISON_API_BASE_URL: "https://api-dev.prison.service.justice.gov.uk"
    COMMUNITY_API_BASE_URL: "https://community-api.test.probation.service.justice.gov.uk"
    OAUTH_API_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    CASENOTES_API_BASE_URL: "https://dev.offender-case-notes.service.justice.gov.uk"
    WIND_BACK_SECONDS: "10"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    APPLICATION_LISTENER_TOTALDELAYDURATION: "PT1M"
    APPLICATION_LISTENER_DELAYDURATION: "PT30S"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: syscon

  # AWS SQS queues to monitor
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-dev-prisoner_offender_events_queue"
    - "Digital-Prison-Services-dev-prisoner_offender_events_queue_dl"

  rdsAlertsDatabases:
    cloud-platform-60b53562549eb2d2: "prison offender events"
