# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/offender-events
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  enable_whitelist: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: offender-events-dev.prison.service.justice.gov.uk
      cert_secret: offender-events-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  CUSTODY_API_BASE_URL: "https://gateway.t3.nomis-api.hmpps.dsd.io/custodyapi"
  OAUTH_API_BASE_URL: "https://gateway.t3.nomis-api.hmpps.dsd.io/auth"
  WIND_BACK_SECONDS: "10"

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"
