---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: offender-events-preprod.prison.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '19 6 * * 1-5' # Start at 6.19am UTC Monday-Friday
    shutdown: '51 21 * * 1-5' # Stop at 9.51pm UTC Monday-Friday

  env:
    API_BASE_URL_PRISON: "https://prison-api-preprod.prison.service.justice.gov.uk"
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_CASENOTES: "https://preprod.offender-case-notes.service.justice.gov.uk"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    APPLICATION_LISTENER_TOTALDELAYDURATION: "PT45M"
    APPLICATION_LISTENER_DELAYDURATION: "PT10M"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  sqsNumberAlertQueueNames:
    - "Digital-Prison-Services-preprod-prisoner_offender_events_queue"
    - "Digital-Prison-Services-preprod-prisoner_offender_events_queue_dl"

cron:
  # At every 10th minute from 1 through 59 past every hour from 7 through 20 UTC on every day-of-week from Monday through Friday.
  retry_dlqs_schedule: "1-59/10 07-20 * * 1-5"
